### ISSUE TITLE
ReferenceError: Cannot access 'ctx' before initialization

### ISSUE THREAD

**Issue by AdrienLemaire** [enisdenjo/graphql-ws#181]
Our server crashed with the following error

```
/app/node_modules/graphql-ws/lib/server.js:36
                    await (onClose === null || onClose === void 0 ? void 0 : onClose(ctx, code, reason));
                                                                                     ^

ReferenceError: Cannot access 'ctx' before initialization
    at ctx.connectionInitReceived (/app/node_modules/graphql-ws/lib/server.js:36:86)
    at WebSocket.<anonymous> (/app/node_modules/graphql-ws/lib/use/ws.js:85:13)
    at Object.onceWrapper (node:events:472:26)
    at WebSocket.emit (node:events:377:35)
    at WebSocket.emitClose (/app/node_modules/ws/lib/websocket.js:191:10)
    at Socket.socketOnClose (/app/node_modules/ws/lib/websocket.js:850:15)
    at Socket.emit (node:events:365:28)
    at TCP.<anonymous> (node:net:661:12)
```

Looking [at the code](https://github.com/enisdenjo/graphql-ws/blob/c6becd2f1714413f811ba8cb582d158304564d4d/src/server.ts#L525-L529), we see that ctx is passed to the onClose method before being initialized.

My assumption is that since we migrated from subscriptions-transport-ws to graphql-ws, some users are still running an older version of the client code, which sends the subscriptions-transport-ws protocol to graphql-ws instead of the graphql-ws one.

I suppose that moving the ctx initialization before the socket check would avoid servers to crash next time a client sends the wrong protocol in a message.

**Comment by enisdenjo** [comment]
Oh wow, how did that go unnoticed. 🤔

Fix incoming!
