### ISSUE TITLE
Cannot stringify invalid message (apollo + react native)

### ISSUE THREAD

**Issue by louisholley** [enisdenjo/graphql-ws#298]
firstly, thanks for the great package! got it working with our web app and it seems like a big improvement on our previous implementation.

I've copied across the same client code to our react native app and it doesn't seem to be connecting - I can't see anything logging server side so I assume it's entirely a client issue.

with the example client code, I'm getting `Can't find variable: CloseEvent`, and if I log the actual error it shows:
```
Cannot stringify invalid message
at node_modules/graphql-ws/umd/graphql-ws.js:169:23 in stringifyMessage
at node_modules/graphql-ws/umd/graphql-ws.js:331:32 in socket.onopen
```

I'm a bit out of my depth here so no clue how to proceed...any advice would be hugely appreciated!

**Comment by louisholley** [comment]
stupid me - I had botched the connectionParams return value! all good, thanks again so much!
