### ISSUE TITLE
limitCloseReason crash with Cannot read properties of undefined 

### ISSUE THREAD

**Issue by MrDesjardins** [enisdenjo/graphql-ws#441]
**Screenshot**
I only have a trace but that should lead you to where it can fail.

```
Internal error occurred during message handling. Please check your implementation. error in secret or public key callback: getaddrinfo ENOTFOUND login.microsoftonline.com
[1] /Users/pdesjardins/code/redacted/node_modules/graphql-ws/lib/utils.js:52
[1]     return reason.length < 124 ? reason : whenTooLong;
[1]                   ^
[1] TypeError: Cannot read properties of undefined (reading 'length')
[1]     at limitCloseReason (/Users/pdesjardins/code/redacted/node_modules/graphql-ws/lib/utils.js:52:19)
[1]     at WebSocket.<anonymous> (/Users/pdesjardins/code/redacted/node_modules/graphql-ws/lib/use/ws.js:90:56)
[1]     at runMicrotasks (<anonymous>)
[1]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1] [nodemon] app crashed - waiting for file changes before starting…
```

**Expected Behaviour**
To not have a null reference exception. Check if the object has the field or if the error is a string.

**Actual Behaviour**
The `err` is not an object but a string. Accessing `err.message` cause a crash

**Debug Information**
1) This line of code: https://github.com/enisdenjo/graphql-ws/blob/2e6eb138b47bf30220c8048f1ba10f0782ded589/src/use/ws.ts#L149
assumes error is an Error object.
2) In my case, it is unclear since I am using the library via Apollo Subscription but it seems that one of the useServer option that try to perform validation fail. I am using the `import { useServer } from "graphql-ws/lib/use/ws";` code
3) For some reason, the authentication fails and there is from the Azure library a **string** returned has an error.
4) The line ` limitCloseReason(err.message, 'Internal server error')` is not receiving an object but a string. So, it returned `undefined` to the `limitCloseReason` function. undefined does not have `.length`, hence the graphql-ws library crash, which bubble up to node who crash.

**Comment by enisdenjo** [comment]
Hey, thanks for reporting! We should handle _anything_ thrown during the message handling, including primitive values and non-instances of `Error`.

A new release coming soon.
